version: '3.2'

services:
  nginx:
    image: nginx:latest
    container_name: c_nginx
    ports:
      - "8088:80"
    networks:
      casual_network:
        ipv4_address: 130.11.1.2
    volumes:
      - ./docker/nginx/casual_nginx.conf:/etc/nginx/conf.d/casual_nginx.conf

  php:
    build:
      context: docker/php

    container_name: c_php
    ports:
      - "9999:9000"

    networks:
      casual_network:
        ipv4_address: 130.11.1.3

  postgres:
    image: postgres:13.2
    container_name: c_postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=casual
      - POSTGRES_PASSWORD=casual
      - POSTGRES_DB=casual
      - TZ=GMT+2
      - PGTZ=GMT+2

    volumes:
      - casual-pg-data:/var/lib/postgresql/data:rw

    networks:
      casual_network:
        ipv4_address: 130.11.1.4

networks:
  casual_network:
    external: true

volumes:
  casual-pg-data:
    external:
      name: casual-pg-data
