version: '3.2'

services:
  casual_nginx:
    image: nginx:latest #вказуємо з якого образу ми хочемо піднімати контейнери і яку версію будемо використовувати
    container_name: c_nginx #назва по якій потім можна звертатись до контейнера замість id
    ports:
      - "80:80" #правий - це внутріщній порт докера по якому інші сервіси докера звертаються.лівий - це зовнішній порт по якому звертаємось з машигни де запущений докер
# docker run --name c_nginx -p 8888:80 -d nginx:latest - все що вище можна замінити цією командою
    volumes:
      - .:/var/www/casual:rw
      - ./docker/nginx/casual_nginx.conf:/etc/nginx/conf.d/casual_nginx.conf


  casual_php:
    container_name: c_php
    build:
      context: docker/php  #якщо ми використ. свій докер файл.то вказуємо за допомогою context шлях дод докер файлу
    ports:
      - "9000:9000"
    working_dir: /var/www/casual
    volumes:
      - .:/var/www/casual:rw

  casual_postgres:
    image: postgres:13.2
    container_name: c_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=casual
      - POSTGRES_PASSWORD=casual
      - POSTGRES_DB=casual
      - TZ=GMT+2
      - PGTZ=GMT+2

    volumes:
      - casual-pg-data:/var/lib/postgresql/data:rw
      #створюємо volume  вручну.по команді в консолі:docker volume create --name=casual-pg-data
      #по цій команді створюєтьтся папка до якої нам потрібно звернутись через конфіг volumes.
      #крім того створені врочну volumes треба записувати на верхній рівень і оголошувати як external.

volumes:
  casual-pg-data:
    external:
      name: casual-pg-data